on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test job to deploy and delete
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy a test application
        id: nginx_deploy
        uses: ./
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        with:
          kubectl_args: apply -f https://k8s.io/examples/application/deployment.yaml
      - name: Delete a test application
        id: nginx_delete
        uses: ./
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        with:
          kubectl_args: delete -f https://k8s.io/examples/application/deployment.yaml
      # Use the output from the `nginx_deploy` step
      - name: Get the output of the command
        run: echo "The output of ${{ steps.nginx_deploy.outputs.kubectl_result }}"
